### ISSUE TITLE
the "ls" doesn't work

### ISSUE THREAD

**Issue by astraychildmarion** [zpm-zsh/ls#10]
Hi, I installed zpm-zsh/ls by zplug. But I typed "ls" in iTerm2, it show
```
/bin/ls: illegal option -- -
usage: ls [-@ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1%] [file ...]
```
if I typed "where I=ls", it show
```
ls () {
	$_ls ${_ls_params} -C $@
}
/bin/ls
```

my zsh version is `zsh 5.8 (x86_64-apple-darwin20.0)`
I am use `Mac OS Big Sur 11.4` 
my ZPLUG_HOME path is `/opt/homebrew/opt/zplug`

Thank you for reply in advance

**Comment by grigorii-horos** [comment]
This happens because macOS ls is BSD ls, but this plugin depends on GNU ls. 

Please install https://formulae.brew.sh/formula/coreutils

**Comment by astraychildmarion** [comment]
@grigorii-horos thank you, it works.
