### ISSUE TITLE
Error when using when exa is installed

### ISSUE THREAD

**Issue by alex3305** [zpm-zsh/ls#13]
Hi, thanks for all the effort the great plugins ❤️. Much appreciated! However I have an issue when running this plugin when `exa` is installed:

```bash
> ls ~
Option --color has no "tty" setting (choices: always, auto, never)
```

When I remove `exa`, everything seems fine. Also adding a color parameter seems to work fine:

```bash
$ ls ~ --color=auto
 dump/   github/   antigen.zsh
```

Running an `ls` command after uninstalling `exa` works too, but the output isn't nearly as pretty 😞. Is there something I can do on my end? Perhaps a conflicting plugin? Or is this really a bug in this wonderful plugin? Thanks!

**Comment by grigorii-horos** [comment]
Can you update this plugin? I did a fix, but I'm not sure if it works.

**Comment by alex3305** [comment]
Hi @grigorii-horos Thank you for your quick response 😍! I have tested your changes, but unfortunately it doesn't make any difference 😢. 

But, I have found a solution / workaround. When I disable oh-my-zsh from antigen, your plugin seems to work great. Is there perhaps a conflicting oh-my-zsh plugin that you know about? Otherwise maybe this is something to add to your `README.md`?

**Comment by Mystic8b** [comment]
Yeah, same problem

**Comment by nhamlh** [comment]
@alex3305 @Mystic8b For my case, there's an alias `ls=ls --color=tty` defined in /etc/zshrc. I just unalias it before loading the plugin and it worked fine.
@grigorii-horos maybe we need to unalias ls aliases at the beginning of the plugin to avoid this?
How to find where the alias is defined? Use this snippet: `PS4='+%x:%I>' zsh -i -x -c '' |& grep 'color=tty'`
