### ISSUE TITLE
ZSH_LS_BACKEND doesn't work properly

### ISSUE THREAD

**Issue by Spookdot** [zpm-zsh/ls#20]
I was having a problem where I had set ZSH_LS_BACKEND to be extra sure that i was getting the ls I wanted because i have lsd, exa and eza installed. But instead of using those it kept going back to ls. 

Looking at the code from line 14 till 28 (especially line 27) in ls.plugin.zsh it seems that right now when ZSH_LS_BACKEND is set it will actually set the ZSH_LS_BACKEND to ls, which doesn't seem to match the intended behavior of having that variable define which backend should be used 
```zsh
if [[ -z "$ZSH_LS_BACKEND" ]]; then
  if [[ ! -z "$ZSH_LS_PREFER_LS" ]]; then
    ZSH_LS_BACKEND='ls'
  elif (( $+commands[lsd] )); then
    ZSH_LS_BACKEND='lsd'
  elif (( $+commands[eza] )); then
    ZSH_LS_BACKEND='eza'
  elif (( $+commands[exa] )); then
    ZSH_LS_BACKEND='exa'
  else
    ZSH_LS_BACKEND='ls'
  fi
else
  ZSH_LS_BACKEND='ls'
fi
```

**Comment by p1r473** [comment]
I have ZSH_LS_BACKEND set and it still seems to use lsd.... any idea?
`export ZSH_LS_BACKEND="eza" `
