### ISSUE TITLE
What is the theme used in the example picture？

### ISSUE THREAD

**Issue by hwdef** [zpm-zsh/ls#4]
I like this theme,it is energetic,could you please tell me the name ?

**Comment by horosgrisa** [comment]
@hwdef 
First: https://github.com/zpm-zsh/ls#note

Second: I use Tilix with my colour theme https://github.com/zpm-zsh/material-colors/blob/master/SuperMaterial.json

**Comment by hwdef** [comment]
@horosgrisa 
Did you used ohmyzsh?

**Comment by horosgrisa** [comment]
@hwdef No, I use own package manager https://github.com/zpm-zsh/zpm

**Comment by hwdef** [comment]
@horosgrisa  thank you , I will try it.

**Comment by matchai** [comment]
What is the prompt used in the screenshot?
I like the way they represent the elements of git status. 😄

**Comment by grigorii-horos** [comment]
@matchai Hey! I use my own plugin for git https://github.com/zpm-zsh/pr-git
